/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bn_jni_MainActivity_Companion */

#ifndef _Included_com_bn_jni_MainActivity_Companion
#define _Included_com_bn_jni_MainActivity_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
