/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../../soft/android/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_bn_jni_MainActivity */

#ifndef _Included_com_bn_jni_MainActivity
#define _Included_com_bn_jni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_bn_jni_MainActivity_BIND_ABOVE_CLIENT
#define com_bn_jni_MainActivity_BIND_ABOVE_CLIENT 8L
#undef com_bn_jni_MainActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_bn_jni_MainActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_bn_jni_MainActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_bn_jni_MainActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_bn_jni_MainActivity_BIND_AUTO_CREATE
#define com_bn_jni_MainActivity_BIND_AUTO_CREATE 1L
#undef com_bn_jni_MainActivity_BIND_DEBUG_UNBIND
#define com_bn_jni_MainActivity_BIND_DEBUG_UNBIND 2L
#undef com_bn_jni_MainActivity_BIND_EXTERNAL_SERVICE
#define com_bn_jni_MainActivity_BIND_EXTERNAL_SERVICE -2147483648L
#undef com_bn_jni_MainActivity_BIND_IMPORTANT
#define com_bn_jni_MainActivity_BIND_IMPORTANT 64L
#undef com_bn_jni_MainActivity_BIND_INCLUDE_CAPABILITIES
#define com_bn_jni_MainActivity_BIND_INCLUDE_CAPABILITIES 4096L
#undef com_bn_jni_MainActivity_BIND_NOT_FOREGROUND
#define com_bn_jni_MainActivity_BIND_NOT_FOREGROUND 4L
#undef com_bn_jni_MainActivity_BIND_NOT_PERCEPTIBLE
#define com_bn_jni_MainActivity_BIND_NOT_PERCEPTIBLE 256L
#undef com_bn_jni_MainActivity_BIND_WAIVE_PRIORITY
#define com_bn_jni_MainActivity_BIND_WAIVE_PRIORITY 32L
#undef com_bn_jni_MainActivity_CONTEXT_IGNORE_SECURITY
#define com_bn_jni_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_bn_jni_MainActivity_CONTEXT_INCLUDE_CODE
#define com_bn_jni_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_bn_jni_MainActivity_CONTEXT_RESTRICTED
#define com_bn_jni_MainActivity_CONTEXT_RESTRICTED 4L
#undef com_bn_jni_MainActivity_MODE_APPEND
#define com_bn_jni_MainActivity_MODE_APPEND 32768L
#undef com_bn_jni_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_bn_jni_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_bn_jni_MainActivity_MODE_MULTI_PROCESS
#define com_bn_jni_MainActivity_MODE_MULTI_PROCESS 4L
#undef com_bn_jni_MainActivity_MODE_NO_LOCALIZED_COLLATORS
#define com_bn_jni_MainActivity_MODE_NO_LOCALIZED_COLLATORS 16L
#undef com_bn_jni_MainActivity_MODE_PRIVATE
#define com_bn_jni_MainActivity_MODE_PRIVATE 0L
#undef com_bn_jni_MainActivity_MODE_WORLD_READABLE
#define com_bn_jni_MainActivity_MODE_WORLD_READABLE 1L
#undef com_bn_jni_MainActivity_MODE_WORLD_WRITEABLE
#define com_bn_jni_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef com_bn_jni_MainActivity_RECEIVER_VISIBLE_TO_INSTANT_APPS
#define com_bn_jni_MainActivity_RECEIVER_VISIBLE_TO_INSTANT_APPS 1L
#undef com_bn_jni_MainActivity_DEFAULT_KEYS_DIALER
#define com_bn_jni_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef com_bn_jni_MainActivity_DEFAULT_KEYS_DISABLE
#define com_bn_jni_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_bn_jni_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_bn_jni_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef com_bn_jni_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_bn_jni_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_bn_jni_MainActivity_DEFAULT_KEYS_SHORTCUT
#define com_bn_jni_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_bn_jni_MainActivity_RESULT_CANCELED
#define com_bn_jni_MainActivity_RESULT_CANCELED 0L
#undef com_bn_jni_MainActivity_RESULT_FIRST_USER
#define com_bn_jni_MainActivity_RESULT_FIRST_USER 1L
#undef com_bn_jni_MainActivity_RESULT_OK
#define com_bn_jni_MainActivity_RESULT_OK -1L
#undef com_bn_jni_MainActivity_MAX_NUM_PENDING_FRAGMENT_ACTIVITY_RESULTS
#define com_bn_jni_MainActivity_MAX_NUM_PENDING_FRAGMENT_ACTIVITY_RESULTS 65534L
#undef com_bn_jni_MainActivity_MSG_RESUME_PENDING
#define com_bn_jni_MainActivity_MSG_RESUME_PENDING 2L
/*
 * Class:     com_bn_jni_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bn_jni_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_bn_jni_MainActivity
 * Method:    stringFromJNI2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bn_jni_MainActivity_stringFromJNI2
  (JNIEnv *, jobject);

/*
 * Class:     com_bn_jni_MainActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_bn_jni_MainActivity_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
extern "C"
JNIEXPORT void JNICALL
Java_com_bn_jni_MainActivity_callJavaInstaceMethod(JNIEnv *env, jobject thiz);


extern "C"
JNIEXPORT jstring JNICALL
Java_com_bn_jni_MainActivity_callJavaStaticMethod2(JNIEnv *env, jobject thiz, jstring from,
                                                     jint index);


extern "C"
JNIEXPORT jstring JNICALL
Java_com_bn_jni_MainActivity_callJavaStaticMethod3(JNIEnv *env, jobject thiz, jstring from,
                                                     jint index);


extern "C"
JNIEXPORT jstring JNICALL
Java_com_bn_jni_MainActivity_callJavaInstanceMethod3(JNIEnv *env, jobject thiz, jstring from,
                                                     jint index);

extern "C"
JNIEXPORT jstring JNICALL
Java_com_bn_jni_MainActivity_callJavaInstanceMethod4(JNIEnv *env, jobject thiz, jstring from,
                                                     jint index);